name: Run tests and deploy to prod

on:
  push:
    branches:
      - 'main'
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Using Node.js 20

      - name: Install dependencies
        run: npm ci  # Use npm ci for faster, clean installs

      - name: Run tests
        run: npm run test

      - name: Run lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Deploy to prod in AWS Cloud
        run: echo "Don't have time, but would include a step to build docker image and push to AWS ECR or push to an AWS S3 bucket and reset cache of it"